### ISSUE TITLE
Unable to Run React Example Project Template

### ISSUE THREAD

**Issue by wkhori** [dappforce/subsocial-react-example#2]
Followed instructions in readme but unable to run development server. Getting this ReferenceError in Safari.

<img width="972" alt="Screen Shot 2022-01-08 at 8 35 04 PM" src="https://user-images.githubusercontent.com/34014558/148666946-dd02c580-98eb-4e72-b208-f85ca7d40c10.png">

In Chrome, I get this error in console `WebSocket connection to 'wss://rpc.subsocial.network/' failed:` and a blank page renders. 

I am also able to run storybook but none of the stories render in the Canvas and I see the same websocket error.
 
Seeing this warning in command line as well: 
```
(node:21726) [DEP0128] DeprecationWarning: Invalid 'main' field in '.../dev/subsocial/subsocial-react-example/node_modules/@subsocial/api/node_modules/@subsocial/utils/package.json' of 'build/index.js'. Please either fix that or report it to the module author
Could not find files for / in .next/build-manifest.json
```

**Comment by olehmell** [comment]
Hello @wkhori, we recommend trying `yarn`.

This bug we will try to fix it soon.
